src/Entity/Quiz.php
<?php

namespace App\Entity;

use Symfony\Component\HttpFoundation\File\File;
use App\Repository\QuizRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=QuizRepository::class)
 * @Vich\Uploadable
 */
class Quiz
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=500)
     * @var string
     */
    private $Image;

    /**
     * @Vich\UploadableField(mapping="image_upload", fileNameProperty="Image")
     * @var File
     */
    private $ImageFile;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="Quizzes")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="quiz")
     */
    private $questions;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Score::class, mappedBy="Quizs")
     */
    private $scores;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->scores = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addQuiz($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeQuiz($this);
        }

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setQuiz($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getQuiz() === $this) {
                $question->setQuiz(null);
            }
        }

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->ImageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->ImageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function __toString(): string
    {
        return $this->Titre; // Remplacez 'Titre' par le nom de la propriété que vous souhaitez afficher.
    }

    public function getQuestionsArray(): array
    {
        return $this->questions->toArray();
    }

    /**
     * @return Collection<int, Score>
     */
    public function getScores(): Collection
    {
        return $this->scores;
    }

    public function addScore(Score $score): self
    {
        if (!$this->scores->contains($score)) {
            $this->scores[] = $score;
            $score->setQuiz($this);
        }

        return $this;
    }

    public function removeScore(Score $score): self
    {
        if ($this->scores->removeElement($score)) {
            // set the owning side to null (unless already changed)
            if ($score->getQuiz() === $this) {
                $score->setQuiz(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToMany(targetEntity=Quiz::class, inversedBy="Quizes")
     */
    private $Quizzes;

    /**
     * @ORM\OneToMany(targetEntity=Score::class, mappedBy="user")
     */
    private $scores;

    public function __construct()
    {
        $this->Quizzes = new ArrayCollection();
        $this->scores = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Quiz>
     */
    public function getQuizzes(): Collection
    {
        return $this->Quizzes;
    }

    public function addQuiz(Quiz $quiz): self
    {
        if (!$this->Quizzes->contains($quiz)) {
            $this->Quizzes[] = $quiz;
        }

        return $this;
    }

    public function removeQuiz(Quiz $quiz): self
    {
        $this->Quizzes->removeElement($quiz);

        return $this;
    }

    /**
     * @return Collection<int, Score>
     */
    public function getScores(): Collection
    {
        return $this->scores;
    }

    public function addScore(Score $score): self
    {
        if (!$this->scores->contains($score)) {
            $this->scores[] = $score;
            $score->setUser($this);
        }

        return $this;
    }

    public function removeScore(Score $score): self
    {
        if ($this->scores->removeElement($score)) {
            // set the owning side to null (unless already changed)
            if ($score->getUser() === $this) {
                $score->setUser(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->email; // Replace 'content' with the property you want to display.
    }
}

src/Form/QuizType.php
<?php

namespace App\Form;

use App\Entity\Quiz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuizType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('Description')
            ->add('Image')
            ->add('updatedAt')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quiz::class,
        ]);
    }
}

src/Controller/QuizController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Quiz;
use App\Form\QuizType;
use App\Repository\QuizRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Score;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use App\Entity\Question;
use App\Entity\Answers;

/**
 * @Route("/quiz")
 */
class QuizController extends AbstractController
{
    /**
     * @Route("/", name="app_quiz_index", methods={"GET"})
     */
    public function index(QuizRepository $quizRepository): Response
    {
        return $this->render('quiz/index.html.twig', [
            'quizzes' => $quizRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_quiz_new", methods={"GET", "POST"})
     */
    public function new(Request $request, QuizRepository $quizRepository): Response
    {
        $quiz = new Quiz();
        $form = $this->createForm(QuizType::class, $quiz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quizRepository->add($quiz, true);

            return $this->redirectToRoute('app_quiz_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quiz/new.html.twig', [
            'quiz' => $quiz,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_quiz_show", methods={"GET"})
     */
    public function show(Quiz $quiz): Response
    {
        return $this->render('quiz/quiz.html.twig', [
            'quiz' => $quiz,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_quiz_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Quiz $quiz, QuizRepository $quizRepository): Response
    {
        $form = $this->createForm(QuizType::class, $quiz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quizRepository->add($quiz, true);

            return $this->redirectToRoute('app_quiz_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quiz/edit.html.twig', [
            'quiz' => $quiz,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_quiz_delete", methods={"POST"})
     */
    public function delete(Request $request, Quiz $quiz, QuizRepository $quizRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $quiz->getId(), $request->request->get('_token'))) {
            $quizRepository->remove($quiz, true);
        }

        return $this->redirectToRoute('app_quiz_index', [], Response::HTTP_SEE_OTHER);
    }


    //calculer

    /**
     * @Route("/{id}/sub", name="user_submit_quiz", methods={"POST"})
     */
    public function submitQuiz(Request $request, Security $security, $id, EntityManagerInterface $entityManager): Response
    {
        // Récupérer l'utilisateur connecté
        $user = $security->getUser();

        if (!$user) {
            throw new AccessDeniedException('Vous devez être connecté pour soumettre le quiz.');
        }

        $quiz = $entityManager->getRepository(Quiz::class)->find($id);

        if (!$quiz) {
            throw $this->createNotFoundException('Le quiz demandé n\'existe pas.');
        }

        $questions = $quiz->getQuestions();
        $totalQuestions = count($questions);
        $correctAnswers = 0;

        foreach ($questions as $question) {
            $questionId = $question->getId();
            $submittedAnswerId = $request->request->get('question' . $questionId);

            if ($submittedAnswerId) {
                $submittedAnswer = $entityManager->getRepository(Answers::class)->find($submittedAnswerId);

                if (!$submittedAnswer) {
                    throw $this->createNotFoundException('La réponse soumise n\'existe pas.');
                }

                if ($submittedAnswer->getIsCorrect()) {
                    $correctAnswers++;
                }
            }
        }

        $score = ($correctAnswers / $totalQuestions) * 100;

        $scoreEntity = new Score();
        $scoreEntity->setUser($user);
        $scoreEntity->setScore($score);
        $scoreEntity->setQuiz($quiz);

        $entityManager->persist($scoreEntity);
        $entityManager->flush();

        return $this->render('quiz/result.html.twig', [
            'score' => $scoreEntity, // Utilisez l'objet $scoreEntity au lieu de $score
        ]);
    }
}

templates/quiz/_delete_form.html.twig
<form method="post" action="{{ path('app_quiz_delete', {'id': quiz.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quiz.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quiz/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quiz/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quiz{% endblock %}

{% block body %}
    <h1>Edit Quiz</h1>

    {{ include('quiz/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_quiz_index') }}">back to list</a>

    {{ include('quiz/_delete_form.html.twig') }}
{% endblock %}

templates/quiz/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quiz{% endblock %}

{% block body %}
    <h1>Create new Quiz</h1>

    {{ include('quiz/_form.html.twig') }}

    <a href="{{ path('app_quiz_index') }}">back to list</a>
{% endblock %}

templates/quiz/quiz.html.twig
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Université Privée De Fès</title>
		<meta content="width=device-width, initial-scale=1.0" name="viewport">
		<meta content="Free HTML Templates" name="keywords">
		<meta
		content="Free HTML Templates" name="description">

		<!-- Favicon -->
		<link
		href="img/favicon.ico" rel="icon">

		<!-- Google Web Fonts -->
		<link rel="preconnect" href="https://fonts.gstatic.com">
		<link
		href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

		<!-- Font Awesome -->
		<link
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

		<!-- Libraries Stylesheet -->
		<link
		href="{{asset('lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">

		<!-- Customized Bootstrap Stylesheet -->
		<link href="{{asset('css/quiz.css')}}" rel="stylesheet">
	</head>

	<body>
		<!-- Topbar Start -->
		<div class="container-fluid bg-dark">
			<div style="background-color: #b11b81" class="row py-2 px-lg-5">
				<div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
					<div class="d-inline-flex align-items-center text-white">
						<small>
							<i class="fa fa-phone-alt mr-2"></i>
							+212 535 610 320</small>
						<small class="px-3">|</small>
						<small>
							<i class="fa fa-envelope mr-2"></i>info@upf.ac.ma</small>
					</div>
				</div>
				<div class="col-lg-6 text-center text-lg-right">
					<div class="d-inline-flex align-items-center">
						<a class="text-white px-2" href="">
							<i class="fab fa-facebook-f"></i>
						</a>
						<a class="text-white px-2" href="">
							<i class="fab fa-twitter"></i>
						</a>
						<a class="text-white px-2" href="">
							<i class="fab fa-linkedin-in"></i>
						</a>
						<a class="text-white px-2" href="">
							<i class="fab fa-instagram"></i>
						</a>
						<a class="text-white pl-2" href="">
							<i class="fab fa-youtube"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- Topbar End -->


		<!-- Navbar Start -->
		<div class="container-fluid p-0">
			<nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5">
				<a href="{{ path('app_index') }}" class="navbar-brand ml-lg-3">
					<img src="{{asset('img/logo_upf.png')}}">
				</a>
				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
					<div class="navbar-nav mx-auto py-0">
						<a href="{{ path('app_index') }}" class="nav-item nav-link active">Home</a>
						<a href="about.html" class="nav-item nav-link">About</a>
						<a href="course.html" class="nav-item nav-link">Courses</a>
						<div class="nav-item dropdown">
							<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
							<div class="dropdown-menu m-0">
								<a href="detail.html" class="dropdown-item">Course Detail</a>
								<a href="feature.html" class="dropdown-item">Our Features</a>
								<a href="team.html" class="dropdown-item">Instructors</a>
								<a href="testimonial.html" class="dropdown-item">Testimonial</a>
							</div>
						</div>
						<a href="contact.html" class="nav-item nav-link">Contact</a>
					</div>
					<div class="nav-item dropdown">
						{% if app.user %}
							<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Bienvenue,
								{{ app.user.username }}</a>
							<div class="dropdown-menu m-0">
								<a href="{{ path('app_logout') }}" value="{{ path('app_logout') }}" class="dropdown-item">Déconnexion</a>

							</div>
						{% endif %}


					</div>
				</nav>
			</div>
			<!-- Navbar End -->


			<!-- Header Start -->
			<div class="jumbotron jumbotron-fluid position-relative overlay-bottom" style="margin-bottom: 90px;">
				<div class="container text-center my-5 py-5">

					<h1 class="text-white display-1 mb-5">{{ quiz.Titre }}</h1>

				</div>
			</div>
			<!-- Header End -->


			<!-- Quiz Form Start -->
			<div class="container-fluid py-5">
				<div class="container py-5">
					<div class="row align-items-center">
						<div class="col-lg-5 mb-5 mb-lg-0">
							<div style="background-color: crimson;" class="bg-light d-flex flex-column justify-content-center px-5 quiz-contact" id="quiz-contact">
								<div class="d-flex align-items-center mb-5">

									<div class="mt-n1"></div>
								</div>
								<div class="d-flex align-items-center mb-5">

									<div class="mt-n1"></div>
								</div>
								<div class="d-flex align-items-center">

									<div class="mt-n1"></div>
								</div>
							</div>
						</div>

						<script>
							// Calculate the height dynamically based on the number of questions
var quizContact = document.getElementById("quiz-contact");
var questionCount = {{ quiz.questions|length }};
var minHeight = (questionCount * 170) + 180;
quizContact.style.minHeight = minHeight + "px";
						</script>

						<div class="col-lg-7">
							<div class="section-title position-relative mb-4">
								<h6 class="d-inline-block position-relative text-secondary text-uppercase pb-2">Quiz Form</h6>
								<h1 class="display-4">{{ quiz.Titre }}</h1>
							</div>
							<div class="quiz-form">
								<form method="POST" action="{{ path('user_submit_quiz', { 'id': quiz.id }) }}">
									<div class="d-flex flex-wrap">
										{% for question in quiz.questions %}
											<div class="question flex-fill">
												<span class="question-text">Question
													{{ loop.index }}:<br>{{ question.content }}</span>
												{% for answer in question.answers %}
													<div class="answers">
														<label class="answer-option">
															<input type="radio" id="question{{ question.id }}_{{ answer.id }}" name="question{{ question.id }}" value="{{ answer.id }}" required>
															<span class="answer-text">{{ answer.content }}</span>
														</label>
													</div>
												{% endfor %}
											</div>
										{% endfor %}
									</div>

									<div class="submit-button">
										<button class="btn btn-primary py-3 px-5" style="background-color: #b11b81" type="submit">Submit</button>
									</div>
								</form>


							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Quiz Form End -->


			<!-- Footer Start -->
			<div class="container-fluid position-relative overlay-top bg-dark text-white-50 py-5" style="margin-top: 90px;">
				<div class="container mt-5 pt-5">
					<div class="row">
						<div class="col-md-6 mb-5">
							<a href="index.html" class="navbar-brand">
								<img src="{{asset('img/logo-2018new2.png')}}"/>
							</a>
							<p class="m-0">Première Université Privée à Fès à avoir obtenu le statut de la Reconnaissance par l’Etat en mai 2018, l’UPF délivre désormais des diplômes automatiquement équivalents aux diplômes de l’Etat. Elle œuvre depuis 2006 à offrir des formations d’excellence dans les métiers d’avenir</p>
						</div>
						<div class="col-md-6 mb-5">
							<h3 class="text-white mb-4">Newsletter</h3>
							<div class="w-100">
								<div class="input-group">
									<input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
									<div class="input-group-append">
										<button style="background-color: #b11b81" class="btn btn-primary px-4">Sign Up</button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 mb-5">
							<h3 class="text-white mb-4">Rejoindre - Nous</h3>
							<p>
								<i class="fa fa-map-marker-alt mr-2"></i>Lotissement Quaraouiyine Route Ain Chkef, Fès 30000</p>
							<p>
								<i class="fa fa-phone-alt mr-2"></i>+212 535 610 320</p>
							<p>
								<i class="fa fa-envelope mr-2"></i>
								info@upf.ac.ma</p>
							<div class="d-flex justify-content-start mt-4">
								<a class="text-white mr-4" href="https://freewebsitecode.com/">
									<i class="fab fa-2x fa-twitter"></i>
								</a>
								<a class="text-white mr-4" href="https://facebook.com/freewebsitecode/">
									<i class="fab fa-2x fa-facebook-f"></i>
								</a>
								<a class="text-white mr-4" href="https://freewebsitecode.com/">
									<i class="fab fa-2x fa-linkedin-in"></i>
								</a>
								<a class="text-white" href="https://youtube.com/freewebsitecode/">
									<i class="fab fa-2x fa-youtube"></i>
								</a>
							</div>
						</div>
						<div class="col-md-4 mb-5">
							<h3 class="text-white mb-4">Our Courses</h3>
							<div class="d-flex flex-column justify-content-start">
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Web Design</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Apps Design</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Marketing</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Research</a>
								<a class="text-white-50" href="#">
									<i class="fa fa-angle-right mr-2"></i>SEO</a>
							</div>
						</div>
						<div class="col-md-4 mb-5">
							<h3 class="text-white mb-4">Quick Links</h3>
							<div class="d-flex flex-column justify-content-start">
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Privacy Policy</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Terms & Condition</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Regular FAQs</a>
								<a class="text-white-50 mb-2" href="#">
									<i class="fa fa-angle-right mr-2"></i>Help & Support</a>
								<a class="text-white-50" href="#">
									<i class="fa fa-angle-right mr-2"></i>Contact</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid bg-dark text-white-50 border-top py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
				<div class="container">
					<div class="row">
						<div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
							<p class="m-0">Copyright &copy;
								<a class="text-white" href="https://freewebsitecode.com/">Université Privée à Fès</a>. All Rights Reserved.
							</p>
						</div>
						<div class="col-md-6 text-center text-md-right">
							<p class="m-0">Designed by
								<a class="text-white" href="https://freewebsitecode.com">Université Privée à Fès</a>
							</p>
						</div>
					</div>
				</div>
			</div>
			<!-- Footer End -->


			<!-- Back to Top -->
			<a href="#" style="background-color: #b11b81" class="btn btn-lg btn-primary rounded-0 btn-lg-square back-to-top">
				<i class="fa fa-angle-double-up"></i>
			</a>


			<!-- JavaScript Libraries -->
			<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
			<script src="{{asset('lib/easing/easing.min.js')}}"></script>
			<script src="{{asset('lib/waypoints/waypoints.min.js')}}"></script>
			<script src="{{asset('lib/counterup/counterup.min.js')}}"></script>
			<script src="{{asset('lib/owlcarousel/owl.carousel.min.js')}}"></script>

			<!-- Template Javascript -->
			<script src="{{asset('js/main.js')}}"></script>
		</body>
	</body>
</html>